### ISSUE TITLE
vcfToArchive.py needs a slight tweak

### ISSUE THREAD

**Issue by jacmarjorie** [OpenGenomics/mc3#1]
I have a PR coming for the reheadering which will fix the vcf reheadering. I am however getting this error:

```
[varscan.snp.genome.wustl.edu.TCGA-W5-AA33.vcf] VCF header validation error: SAMPLE header value '<"--min-coverage 8 --min-coverage-normal 8 --min-coverage-tumor 6 --min-var-freq 0.1 --min-freq-for-hom 0.75 --normal-purity 1.0 --tumor-purity 1.0 --p-value 0.99 --somatic-p-value 0.05">' for key 'softwareParam' contains whitespace and must be enclosed in double quotes    [archive ucsc.edu_BRCA.Multicenter_mutation_calling_MC3.Level_2.1.0.0]
```

I believe the reason this is complaining is because the validator is expecting this format (as quoted from the TCGA format guide:

"If multiple software parameters are defined, comma-separated list of paramName=paramValue pairs should be used."

This becomes incompatible with line 124 in vcfToArchive.py:

```
params = dict(item.split("=") for item in sampleLine.split(","))
```

Writing the software params as --param paramValue does not bother vcfProcessLog, but is more picky for the softwareParam portion.

**Comment by Jeltje** [comment]
Can you give me an example of the actual input line you're trying to parse?
Or, even better, email a complete VCF header so I can test?

Thanks!

**Comment by jacmarjorie** [comment]
More details (from email thread):

Traceback (most recent call last):
  File "/home/jac/mc3/scripts/vcfToArchive.py", line 423, in <module>
    main()
  File "/home/jac/mc3/scripts/vcfToArchive.py", line 388, in main
    sdrfObjectList = sdrfFromVcf(os.path.join(patient, vcfFile), outData)
  File "/home/jac/mc3/scripts/vcfToArchive.py", line 207, in sdrfFromVcf
    mySDRF = SDRF(line)    # create SDRF object
  File "/home/jac/mc3/scripts/vcfToArchive.py", line 96, in **init**
    self.sampleSDRF(fromSample)
  File "/home/jac/mc3/scripts/vcfToArchive.py", line 124, in sampleSDRF
    params = dict(item.split("=") for item in sampleLine.split(","))
ValueError: dictionary update sequence element #11 has length 3; 2 is required

from these lines:

##vcfProcessLog=<InputVCF=</home/jac/galaxy/galaxy_og/database/files/000/dataset_309.dat>, InputVCFSource=<varscan>,InputVCFVer=<4.1>, InputVCFParam=<"min-coverage=8,min-coverage-normal=8,min-coverage-tumor=6,min-var-freq=0.1,min-freq-for-hom=0.75,normal-purity=1.0,tumor-purity=1.0,p-value=0.99,somatic-p-value=0.05">>

##SAMPLE=<ID=PRIMARY,Description="Primary Tumor",SampleUUID=f23b3d0d-26a5-4adf-8aec-4994d094465b,SampleTCGABarcode=TCGA-W5-AA33-01A-11D-A417-09,AnalysisUUID=cd5d8895-6b13-450f-993b-bff9943dc0d9,File="9a6ebf433eb4bcb93be593f74ffa1d3b.bam",Platform="Illumina",Source="dbGAP",Accession="dbGaP",softwareName=<varscan>,softwareVer=<2.4.0>,softwareParam=<"min-coverage=8,min-coverage-normal=8,min-coverage-tumor=6,min-var-freq=0.1,min-freq-for-hom=0.75,normal-purity=1.0,tumor-purity=1.0,p-value=0.99,somatic-p-value=0.05">>

##SAMPLE=<ID=NORMAL,Description="Normal sample",SampleUUID=02e2d8b9-8b5a-4bae-8615-76c46d68f44c,SampleTCGABarcode=TCGA-W5-AA33-10A-01D-A41A-09,AnalysisUUID=3118c963-8446-4d4a-8146-6d46f1465780,File="741377430d1d6a7a567f5425abc41ac2.bam",Platform="Illumina",Source="dbGAP",Accession="dbGaP",softwareName=<varscan>,softwareVer=<2.4.0>,softwareParam=<"min-coverage=8,min-coverage-normal=8,min-coverage-tumor=6,min-var-freq=0.1,min-freq-for-hom=0.75,normal-purity=1.0,tumor-purity=1.0,p-value=0.99,somatic-p-value=0.05">>
